repos:
  # Code Formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-added-large-files
        args: ['--maxkb=1000']
        name: Check for large files
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-toml
        name: Check TOML syntax
      - id: debug-statements
        name: Check for debug statements

  # Python Code Formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: Black - Python code formatter
        language_version: python3
        args: ['--line-length=100']

  # Import Sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort - Sort imports
        args: ['--profile', 'black', '--line-length', '100']

  # Linting (without strict docstring checks)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8 - Linter
        args: [
          '--max-line-length=100',
          '--extend-ignore=E203,W503,D100,D101,D102,D103,D104,D200,D205,D400,D401,D402',
          '--exclude=.git,__pycache__,build,dist'
        ]
        additional_dependencies: [
          'flake8-bugbear',
        ]

# Configuration
default_language_version:
  python: python3.12

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
